Revert "Update LICENSE"
mphetens/mphetens.github.io pull request #6
Opened 2024-09-19 07:35 UTC by mphetens

Reverts mphetens/mphetens.github.io#5

2024-09-24 21:45 UTC, amethystens approved these changes

2024-09-24 21:45 UTC, amethystens commented on LICENSE
> -# mphetens.github.io                  GNU GENERAL PUBLIC LICENSE
1 #mphetens.github.io
  GNU GENERAL PUBLIC LICENSE

2024-09-24 21:46 UTC, amethystens approved these changes

2024-09-24 21:48 UTC, amethystens commented
> Reverts mphetens/mphetens.github.io#5

2024-09-24 21:51 UTC, amethystens requested changes
naprawione

2024-09-24 21:56 UTC, amethystens approved these changes

2024-09-25 11:34 UTC, merged

2024-09-25 12:11 UTC, amethystens approved these changes

2024-09-28 07:46 UTC, amethystens commented on LICENSE
1

2024-09-28 07:48 UTC, amethystens reviewed
LICENSE

2024-09-28 07:48 UTC, amethystens commented on LICENSE
LICENSE

2024-09-28 07:48 UTC, amethystens approved these changes

2024-09-28 07:49 UTC, amethystens requested changes
done

2024-09-28 07:50 UTC, amethystens approved these changes

2024-09-28 07:50 UTC, amethystens commented
> Reverts mphetens/mphetens.github.io#5

2024-09-28 08:14 UTC, amethystens approved these changes

2024-09-28 08:15 UTC, amethystens approved these changes

2024-09-28 08:15 UTC, amethystens approved these changes

2024-09-28 08:15 UTC, amethystens approved these changes

2024-09-28 08:17 UTC, amethystens approved these changes

2024-09-28 08:17 UTC, amethystens approved these changes

2024-09-28 08:17 UTC, amethystens commented
> Reverts mphetens/mphetens.github.io#5

2024-09-28 08:17 UTC, amethystens commented
> Reverts mphetens/mphetens.github.io#5

2024-09-28 08:18 UTC, amethystens approved these changes

2024-09-28 08:20 UTC, amethystens approved these changes

2024-09-28 08:20 UTC, amethystens approved these changes

2024-09-28 08:20 UTC, amethystens commented on LICENSE
LICENSE

2024-09-30 13:37 UTC, Clydonight approved these changes

2024-09-30 19:44 UTC, amethystens approved these changes

2024-09-30 19:44 UTC, amethystens commented on LICENSE
> -                       Version 3, 29 June 2007
2024

2024-09-30 19:57 UTC, amethystens approved these changes

2024-09-30 19:57 UTC, amethystens commented on LICENSE
> -# mphetens.github.io                  GNU GENERAL PUBLIC LICENSE
1  +#  mphetens.github.io
  GNU GENERAL PUBLIC LICENSE

2024-09-30 19:59 UTC, amethystens approved these changes

2024-09-30 19:59 UTC, amethystens commented on LICENSE
> -# mphetens.github.io                  GNU GENERAL PUBLIC LICENSE
1  +# mphetens.girhub.io
  GNU GENERAL PUBLIC LICENSE

2024-09-30 20:01 UTC, amethystens approved these changes